### ISSUE TITLE
Can't connect with WordPress site

### ISSUE THREAD

**Issue by gpedro34** [wordup-dev/wordup-connect#1]
Hi there,
I have a staging wordpress installation that I'd like to be able to clone and develop locally.
I have installed in my WordPress instalation:
- wordup-connect
- UpdraftPlus

I have made a backup with UpdraftPlus and wordup-connect detects it and says the backup is alright.

I go to my local machine and run
```bash
wordup install --connect=MY_STAGING_URL --private-key=MY_PRIVATE_KEY --logs
```
All I get is 
```bash
 ›   Error: Could not connect with WordPress website (have you installed the wordup plugin on your server?).
```

Using WordPress 5.2.1

Do I also need to install wordup-cli in the WordPress remote server? I don't currently have SSH access to the machine. Anything else I may be doing wrong?

Does the WP_MAX_MEMORY_LIMIT have a role in the remote download of the backup with this plugin usage? That may be my issue as I have the same problem with other backup plugins.

**Comment by shry** [comment]
> Do I also need to install wordup-cli in the WordPress remote server? 

No you don't need to. But it seems that your WordPress server is not accessible.

Before wordup-cli tries to download the backup from your remote server it pings the server. And this doesn't work on your system. 

Could you please checkout what happens when you try to reach this url in your browser: https://your-staging-domain-name?rest_route=/wordup/v1/setup/

**Comment by gpedro34** [comment]
Hi there,
Thanks for the prompt reply.
When I hit the server with the URL you sent I get...

```json
{
   "code": "rest_no_route",
   "message": "Não foi encontrada nenhuma rota que corresponda ao URL e método de pedido",
   "data": {
      "status": 404
   }
}
```

**Comment by shry** [comment]
You are right, i also thought this is the problem.

When you check: https://your-staging-domain-name/wp-json -> WordPress should list all API endpoints. You could search for _wordup_ and have a look which url endpoints are listed. 

I thought the query API endpoint schema works for every WordPress installation. But i guess it's not like this. Although could you checkout if this works: https://your-staging-domain-name/index.php?rest_route=/wordup/v1/setup/ ?

**Comment by gpedro34** [comment]
@shry I no longer have it installed as I couldn't make it work in that installation, although I just received a warning from the client saying that he got alerted of about +200 lines of code added to functions.php inside all themes installed.

This code handles the connection and key verification for wordup-connect and this is being marked as wp_vcd_malware by some firewalls.

Injecting code into all installed themes doesn't seem a good way to handle this matter.

Perhaps is a necessary step, but maybe a more elegant approach would be to just do it to the theme currently in use and show a warning that there was injected code to the functions.php of the current theme.

**Comment by shry** [comment]
You should definitly check your other plugins and themes. This is **NOT** caused by the wordup-connect plugin, as you can see if you would search this repository.

**Comment by gpedro34** [comment]
Hi, sorry for the late reply but have been pretty busy...  
  
I'm not the kind of guy of asking first and I did search the matter before my last reply and didn't got results pointing to flagged plugins or themes installed but to check for vulnerabilities manually and wpscan global scan didn't showed anything out of the ordinary prior to the changes in functions.php.  
  
I reproduced it by setting a wordup standard installation and installing just this plugin, Updraft, Storefront and WooCommerce in a fresh WordPress installation exposed to the internet with a domain pointed to it and HTTPS setup using a separate nginx-proxy-manager container in docker. After +-3 hours my funtions.php was magically changed too.  
Since then have been running just Updraft in production and migrating manually to local wordup in order to work on this project. No issues in neither production nor development so far...  
  
The wordup project is awesome and I'm using it for a while now...  
The wordup-connect one, worked in 2 other sites I've tested and I loved it so I tried to use it to help in a bigger project and it let me down.  
  
Please @shry don't take my words as if I'm only bitching and/or making stupid accusations...  
This only happened to me with wordup-connect + UpDraft + WooCommerce + Storefront installed.
The other two sites I've mentioned use Oblique and the other some non-woocommerce theme and have very few plugins installed and everything is fine...  
  
Your work help me **A LOT** and I'd like to take the moment to thank you for it but I can't deny what my testing proved to me and so I will have to let wordup-connect mature a bit before using it in WooCommerce projects again, at least in production sites.  
  
When I get the time I will try to do some tests with other WooCommerce themes to see if I can find something that helps pin-point what exactly happened and if I find something I will let you know but everything is okay in that installation since this plugin was uninstalled and the files cleaned, also no other updates happened yet on that installation.  
  
I guess I can also be wrong and this plugin may have not had anything to do with this issue although I would consider that as something extremely improbable as explained above. I believe there is something in here to be found...

**Comment by shry** [comment]
Thank you for your detailed reply. Perhaps i have also overreacted a litte bit, because i'm very focused on security in my projects and i do my very best to publish secure code. 
It's pretty strange that you see this behavior on a clean installation. 
The wordup-connect plugin works pretty easy:

- a WP-Rest API endpoint will be created. This endpoint is secured by a short lived hmac signature. 
- When you are requesting the updraft backup from the CLI you are connecting with the API-Endpoint and the updraft backup will be downloaded from a temporary folder (because usually the updraft folder is not accessible)  
- Thats it. As far as i see it, there is 0% chance for code injections. 

When i google the url you provided, i find this page: https://themecheck.info/score/wordpress-theme-martfury-shared-by-vestathemes-com.html
Its an WooCommerce theme, is there a possibility that you have installed this theme?

**Comment by gpedro34** [comment]
Thanks for reconsidering... I've noticed that you have a strong focus on security. As I said before, I have been working with wordup for a while and the way you handle volumes in there, have saved my ass more times than I'd like to admit... After reviewing your code I also edited the message you downvoted so no one that falls in here gets scared without a reason.  
  
Never heard of that theme before and while I can't guarantee it was never installed in the production machine, as I just recently got the client, I can guarantee if it happened, happened a long time ago during the construction phase of the website, so I highly doubt that is the issue here... But I will ask my client if he ever installed it anyways...  
  
The production installation where this first happened has only Twenty Nineteen, Storefront and a child theme that overwrites a couple of templates of Storefront. And has +50 plugins installed so it would be a mess and extremely time-consuming to point out the problem...  
  
In the clean installation, I left the child theme off as I was sure it wasn't from there and regarding plugins only installed woocommerce, updraft and wordup-connect as mentioned. The only thing I forgot to mention was that this clean installation used Wordpress 5.2.2 and the production machine was using 5.2.1 when this happened.  
  
I will try to find time to run some more tests this week like I said and get back to you, because:
- I also think this is extremely odd.  
- your code is pretty easy to understand and well commented and I don't see any issues with it too  
  
I highly doubt I know more about coding plugins than you do but something that crossed my mind is that you could be overwriting some function of the theme or woocommerce plugin somehow and that may be causing some vulnerability to be exposed when this conjunction happens but I don't know how this could be happening as I think is standard to use the slug as a namespace in your functions and you do exactly that in your code.

**Comment by shry** [comment]
One other reason cloud be that the server itself is corrupted. The domain itself was recently created and it hides its owner. It's for sure a part of a hack or something. Perhaps this hack just overwrites all files on the web server, to inject the domain.
Did you do the clean installation on the same server? 
If yes: you could checkout if on a different machine (perhaps a VM) , with a clean WordPress installation and your 3 plugins the same things are happening.
